lesson14/tickets/config/routes.rb
Rails.application.routes.draw do
  resources :routes
  get 'routes/index'

  root'routes#index'

  resources :railway_stations

  resources :trains

  resources :tickets

  resources :cars

  resources :users

end

lesson14/tickets/app/models/car.rb
class Car < ActiveRecord::Base
  validates :car_type, presence: true

  belongs_to :train
end

lesson14/tickets/app/models/coupe_car.rb
class CoupeCar < Car

end

lesson14/tickets/app/models/economy_car.rb
class EconomyCar <Car
validates :side_upper_seats , :side_lower_seats, presence: true
end

lesson14/tickets/app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
  validates :title, presence: true

  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  has_many :trains, foreign_key: :current_station_id
end

lesson14/tickets/app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base

  belongs_to :railway_station
  belongs_to :route
end

lesson14/tickets/app/models/route.rb
class Route < ActiveRecord::Base
  validates :title, presence: true
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains
end

lesson14/tickets/app/models/ticket.rb
class Ticket < ActiveRecord::Base
    # validates :number, presence: true

    belongs_to :first_station, class_name: 'RailwayStation', foreign_key: :first_station_id
    belongs_to :latest_station, class_name: 'RailwayStation', foreign_key: :latest_station_id
    belongs_to :train
    belongs_to :user
end

lesson14/tickets/app/models/train.rb
class Train < ActiveRecord::Base
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :current_route, class_name: 'Route', foreign_key: :route_id
  has_many :cars, class_name: 'Car', primary_key: :car_id
end

lesson14/tickets/app/models/user.rb
class User < ActiveRecord::Base
  has_many :tickets
end

lesson14/tickets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lesson14/tickets/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to @car
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:id,:car_type)
  end
end

lesson14/tickets/app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to @railway_station
    else
      render :new
    end

  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
      redirect_to railway_stations_path
  end

    private

    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title,:trains)
    end
end

lesson14/tickets/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title, railway_station_ids: [])
  end
end

lesson14/tickets/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render :edit
    end
  end

  def destroy
    @ticket . destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:train_id,:user_id,:first_station_id,:latest_station_id)
  end
end

lesson14/tickets/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end


  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id, :user_id)
    end
end

lesson14/tickets/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to user_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:id,:name)
  end
end

lesson14/tickets/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

lesson14/tickets/app/helpers/application_helper.rb
module ApplicationHelper
end

lesson14/tickets/app/helpers/welcome_helper.rb
module WelcomeHelper
end

lesson14/tickets/app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
    <%= render 'common/errors', resourse:@car %>

    <div class="field">
      <%= f.label :car_type %><br>
      <%= f.text_field :car_type %>
    </div>

    <div class="field">
      <%= f.label :upper_seats %><br>
      <%= f.text_field :upper_seats %>
    </div>

    <div class="field">
      <%= f.label :lower_seats %><br>
      <%= f.text_field :lower_seats %>
    </div>

    <div class="field">
      <%= f.label :train, "Train" %><br>
      <%= f.collection_select :train_id, Train.all, :id, :number %>
    </div>

       <div class="actions">
      <%= f.submit "#{ @car.new_record? ? 'Create' : 'Update'}"%>
    </div>
<% end %>

lesson14/tickets/app/views/cars/edit.html.erb
<h1>Change Car</h1>
    <%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

lesson14/tickets/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
  <tr>
    <th>Type Car</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
      <tr>
        <td><%= car.car_type %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New car', new_car_path %>

lesson14/tickets/app/views/cars/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Add Car</h1>
<%= render 'form', car: @car %>


<%= link_to 'Back', cars_path %>

lesson14/tickets/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car Type:</strong>
  <%= @car.car_type %>
</p>




<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

lesson14/tickets/app/views/common/_errors.html.erb
 <% if resourse.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(resourse.errors.count, "error") %> prohibited this resourse from being saved:</h2>
       <ul>
         <% resourse.errors.full_messages.each do |message| %>
           <li><%= message %></li>
         <% end %>
       </ul>
   </div>
 <% end %>

lesson14/tickets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tickets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p> Udovika Serhey 2016</p>

</body>
</html>

lesson14/tickets/app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
    <%= render 'common/errors', resourse:@ticket %>

    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.collection_select :user_id, User.all, :id, :name %>
    </div>

    <div class="field">
      <%= f.label :train_id, "Train" %><br>
      <%= f.collection_select :train_id, Train.all, :id, :number %>
    </div>

    <div class="field">
      <%= f.label :first_station, "First Station" %>
      <%= f.collection_select :first_station_id, RailwayStation.all, :id, :title %>
    </div>

    <div class="field">
      <%= f.label :latest_station, "Latest Station" %>
      <%= f.collection_select :latest_station_id, RailwayStation.all, :id, :title %>
    </div>
       <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

lesson14/tickets/app/views/tickets/edit.html.erb
<h1>Change Car</h1>
    <%= render 'form', car: @ticket %>

<%= link_to 'Back', ticket_path %>

lesson14/tickets/app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
  <tr>
    <th>Ticket</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.user.name %></td>
        <td><%= ticket.train.number %></td>
        <td><%= ticket.first_station.title %></td>
        <td><%= ticket.last_station.title %></td>

        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New ticket', new_ticket_path %>

lesson14/tickets/app/views/tickets/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Add stations</h1>
<%= render 'form', ticket: @ticket %>


<%= link_to 'Back', tickets_path %>

lesson14/tickets/app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @ticket.user.name if @ticket.user %>
  <%= @ticket.train.number if @ticket.train %>
  <%= @ticket.first_station.title if @ticket.first_station %>
  <%= @ticket.latest_station.title if @ticket.latest_station  %>

</p>




<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

lesson14/tickets/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>